// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://epqfhnvuxxxolkielgxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVwcWZobnZ1eHh4b2xraWVsZ3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3OTMyOTksImV4cCI6MjA2NzM2OTI5OX0.e3f-9V9bp6-Nk_qlAX5ZMRdgZv72NsvVF7wa6wK5V3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});